language: java
jdk:
- openjdk10
install: "/bin/true"
script: mvn clean install -q -B
cache:
  directories:
  - "$HOME/.cache"
env:
  global:
  - secure: slFtSEMvEa3PD442sFMdknX0K7wVWT+M0ZctXKiVnRf7I1FdkbwuyrTP4/AxmOWjWg1p3Bgy/Gb+QtG+WAGOsizg/rGjW+ZXiIkV66sP6Uv0hcvsJql8vO34YADtjSivzaHKHHZyIoCiMRBsuAXK/Bt5XqAAtT/SKu/G7P8GuHxUCbjLTimBYVWrFcwgTsftb2Meo9Ijl2ePAB/GJQpN9NAMN2l7EkLscSH4Oh4AwJHGeZylRavHF8vyGVuP9LVDiTkg5lCgsHhJF0GQ9VAnNmCA17JRfdRceQyY+KdBeCPXnaRnpgVzYdL/98Io7BGdD5UD74xy9Ssr4jbWD0JiEndOOodeCdka6Z/rQzXS9cpJuGqZVSzy8Pw/TuqNkBubq2gQdTujJ/VNUiQUhaEWhOfHj0zoEGpB5uIFl/SLDNQikgbOcfQUqcv5QfdJMJprh8Tne8g5otz/s7h3riFqD4ZaoYUI3eUM9nNVBSDALPlpAO9LkA2gWfpXxcpkYJqfKZwbv2CUxhlh5MqvtDNisUOXk1hLxPMCNuKmLTmCv043ZkVtLBGJxZ9jkAlKDWnkFryc9pEzptTqujTzHVXuOCURfknwgihGBauEouA28egKdsB0wwzkRsC+cyURngVDRmXnf3lqcXgii83gcnpIJuLS1jvfQ6bJHxGpRfvHKjw=
  - secure: MhuvEMkWvR63tqapzD1Cp/ktdw11jwrQgIv3mw9OjUT3pOa9G1WJpwVCcev0HOtJPLNKW1Pp/bH66/oEgmpFyurKdwVfv0cO0bPJIbFAC1wa6yYj+0tOKGHAhfrpA1b3fHUZaffv47DXJ45COlj3OnlVoeaYUgINjX9um4vUWhccWo8tT0XQtOE5UtySJXBoh+Q5FZ5CMLe4nFjWCIytUoirvTMaOg20CEj1aoVvjv2gt4DwfTT91li7NP9FhttcWTADh7VX00VH00x44G6Crc48ZL0siemlwWiqDMv/prYPmBiLMdA2NNF014aMQiPKRH5ZNqvAq37vU1/LmorRl/hbUPSGEEmBrE8WFFF+A+jsWjQICsAPrMXlV1wLJ3K8o5AIhLPwwbTZciyRKDU6yqghauK7PVSJ7JkvinWVF/ad1HuAuWHl+JJOwUvHcV6Y+Twemjx0pvlwgt4o5Q4Rk3fHbJVUZzVWGJtDTy9zJzI5NrRI01E2QWCXbOrPCCvKn3KRaBqKv669mSaE8rpnycRurOExXkNDZinFnZe1OC1ru1BxqMc4Ar4oBXT/wn1Roc/K05fV6kQauu70TJjlWvag/tfkW8ZJnGfGJ3HJbAxArl3S2MqcND78EbpI37HrFUNMxB0qSSQI4C1a4mHLk18Nb8pMIvyqwGScrO2LysQ=
  - secure: akj5uyXsYfqu0/66swLqSBvQHcayA6T4TGWz5yMJtJrAWj8CV8O2u6ECRFcpvi0Qf5wj7GGJSLJ40ZoAFO3VwKssQr0LdKHGM29oJz0yIZKzwZOE40uE7jfJ/X0sRzyxm0ij5QRBSQM7XhiEKgK1Q5ugCOKRphsJTnRD6bCJyuAFQSn1/a8PuvcQtYqE8RvR220/jkcuJjFtBtErrbLnAyEkHnCABm5IC7aHqXLnQna2Qmlfij1J5bm5diYQYXreW4A/A21EK4hLnfeFtCntnvdctExv5bayJc8KZLZM7akasVe9+GNSFU5KasJ6hzXG8k1W0Y0CXVRzAkBsKH3SBuos/rsT2AcFLxzCCLfkEYI82+ig/q/NIIcB06PtAS17Jyx/xcLbLvEwNTRH4IJ0F62VvE5GcqslQlhLCIoZMEbTw1A9yysH+6jfPZSJd9o3isn7YYbNcXPNVi8g1sTeY3h28U0ZB+FTLThRt591cyXPEDWhn5RACfmjobd4X8WPuiIiyyVnFXpM7fZeWbaFN8McscMyhO7o4aiml8YtsdCrYfu3X+AxBa3wpJHm4OAf53RHdUsNz3W/9EfmwEqHcl0/g/bNQUWIisQL9TS5qApJ/tMH33XA82/vhsvbrNQFs912kUsnLRlItO14quiFhbmWys44rNOqOvoW7pn7PJk=
  - secure: JdWagC7iWfUHDeHw1Z9HYjpaZoZSYBls3Y85HDwQPQK4P+ogRg9UBgDi1U1N5Dynpf53PQzKmO/5AE/i+MG0zmza30WT5xf48lO0nbR/0dzMoSk5IIgshsmVFsCMobxmsHpMlgMLvZmIM07ZEMCM6GOSZ+kWqnlOddO0DI07gJ4AnQQjJUOTT9l3mYKyaAc9qotEcvoF2ilneMdIO2kzb/WCFq88B1Cq3tuBpMEpBHTQULactRuKlW14JESnYdUQeKde7vBvHNxuC2PnmCcmaRKhna6CLf03rRIP+pkOSpZOad79/GQnqPGznl0U/w1tlai3uEjK2SjAN+yNDFj9mP1YH+9Tm4N5SCnikbuh3GajUPbIAZaM6xOuSoGJQfIp3Z0Kf9zzaqMl3PeCD76v8sl9UMcCCaNuQd53Mw19HF3LHZ+8h/oSehcRoCPpm8kcU4RKgt1xhOh3rhElAlz9pwJk/ZXMY8LDrQaAkZD7BwEUlDj4AdJyFl2bEDu9v/UpXK4S0r+akQUvrgti1awfLd5iQkwSZGfqRqp6PbUaFIu+u0XaEbK7Rn/9pNcQINLIcTUWsNEMWdOsJ3EmaNBnO/1WB5Zy+GlxK5/2yU7csocme+/2+RuJ+gvQaUH7NP/Liq58pgbrxlo7PqZZqkVlqNvIkC/hGJfHpeTvusLaJE8=
before_deploy:
- openssl aes-256-cbc -K $encrypted_f094dd62560a_key -iv $encrypted_f094dd62560a_iv
  -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
deploy:
- skip_cleanup: true
  provider: script
  script: "./deploy"
  on:
    branch: master
- skip_cleanup: true
  provider: script
  script: "./deploy"
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_4f0d00631887_key -iv $encrypted_4f0d00631887_iv
  -in gpg.asc.enc -out .travis/gpg.asc -d
